name: xhealth-default
channels: [conda-forge, defaults]
dependencies:
  - python=3.9
  - numpy>=1.21
  - pandas>=1.3
  - scikit-learn>=1.0,<1.2
  - matplotlib>=3.4
  - seaborn>=0.11
  - joblib>=1.1
  - pip
  - pip:
      - xgboost>=1.6
